import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { ProjectError } from "./errors.ts";

// Typst label characters; keys here are `{author}{year}{keyword}`, but a superset is accepted.
const LABEL = "[A-Za-z][A-Za-z0-9_:.+-]*";
// `#cite(<key>, …)` only: other `<label>`s (headings, figures) are not citations.
const CITE_CALL = new RegExp(`cite\\s*\\(\\s*<(${LABEL})>`, "g");
const BARE_CITE = new RegExp(`@(${LABEL})`, "g");

const BLOCK_COMMENT = /\/\*[\s\S]*?\*\//g;
const LINE_COMMENT = /\/\/[^\n]*/g;
const STRING = /"(?:[^"\\]|\\.)*"/g;

// A whole entry: `@type{key,` up to a `}` alone at the start of a line. Copying the matched text
// keeps each entry verbatim (field order, formatting, non-standard fields).
const ENTRY = /@(\w+)\{([^,]+),[\s\S]*?\n\}/g;

export interface SubsetResult {
  kept: number;
  total: number;
  missing: string[];
}

/**
 * Blank out comments and string literals so `form: "prose"` or `// @x` are not read as citations.
 * A regex heuristic, not a Typst tokenizer: raw blocks are not tracked, which is fine because
 * citation keys do not appear inside them in practice.
 */
function stripNoise(text: string): string {
  const blank = (match: string): string => " ".repeat(match.length);
  return text.replace(BLOCK_COMMENT, blank).replace(LINE_COMMENT, blank).replace(STRING, blank);
}

export function citedKeys(typstSource: string): Set<string> {
  const clean = stripNoise(typstSource);
  const keys = new Set<string>();
  for (const pattern of [CITE_CALL, BARE_CITE]) {
    for (const match of clean.matchAll(pattern)) {
      keys.add(match[1] as string);
    }
  }
  return keys;
}

function typFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...typFiles(path));
    } else if (entry.name.endsWith(".typ")) {
      files.push(path);
    }
  }
  return files.sort();
}

export function parseEntries(bib: string): Map<string, string> {
  const entries = new Map<string, string>();
  for (const match of bib.matchAll(ENTRY)) {
    entries.set((match[2] as string).trim(), match[0]);
  }
  return entries;
}

/** Write the entries of `bibliography` cited anywhere under `sourceDir` to `output`. */
export function writeSubset(sourceDir: string, bibliography: string, output: string): SubsetResult {
  if (!statSync(bibliography, { throwIfNoEntry: false })?.isFile()) {
    throw new ProjectError(`bibliography not found: ${bibliography}`);
  }
  const used = new Set<string>();
  for (const file of typFiles(sourceDir)) {
    for (const key of citedKeys(readFileSync(file, "utf8"))) {
      used.add(key);
    }
  }
  const entries = parseEntries(readFileSync(bibliography, "utf8"));
  const sorted = [...used].sort();
  const kept = sorted.filter((key) => entries.has(key));
  const missing = sorted.filter((key) => !entries.has(key));

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(
    output,
    `% Generated by thesis-toolkit from ${bibliography}\n` +
      `% ${kept.length} of ${entries.size} entries used; do not edit.\n\n` +
      kept.map((key) => entries.get(key)).join("\n\n") +
      "\n",
  );
  return { kept: kept.length, total: entries.size, missing };
}
